v4.0.3
From DrDonk

diff --git a/check b/check
--- a/check
+++ b/check
@@ -5,13 +5,24 @@
 #set -e
 #set -x
 
-printf "VMware ESXi Unlocker 4.0.2\n"
+printf "VMware ESXi Unlocker 4.0.3\n"
 printf "==========================\n"
-printf "© 2011-2022 David Parsons\n"
+printf "(c) 2011-2022 David Parsons\n"
 printf "\nChecking unlocker...\n"
 
 # Ensure we only use unmodified commands
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
+
+ESXI=$(vmware -v)
+printf "Current version of ESXi: $ESXI\n"
+
+PATCH=$(cat /etc/unlock.conf)
+printf "Patch built for ESXi: $PATCH\n"
+
+if [[ "$ESXI" != "$PATCH" ]]; then
+  printf "\x1B[41m\x1B[37m>>> ERROR: Mis-matched files please relock/unlock to update patches <<<\x1B[0m\n"
+  exit 1
+fi
 
 printf "Checking VMTAR loaded...\n"
 esxcli system visorfs tardisk list | grep apple.v00 >/dev/null
@@ -31,3 +42,7 @@ then
 else
   printf "vmx not patched\n"
 fi
+
+printf "Checking smcPresent status...\n"
+vim-cmd hostsvc/hosthardware | grep smcPresent | cut -d ',' -f 1 | sed 's/^[ \t]*//'
+exit
